### ISSUE TITLE
安卓13无法授权data

### ISSUE THREAD

**Issue by Guhe-o** [jestyf/GenshinSwitcher#3]
![Screenshot_2023-01-31-09-43-57-613_com google android documentsui](https://user-images.githubusercontent.com/67861307/215638591-832b4211-fc84-4c4a-914b-1e74237a3d20.jpg)
谢谢大佬，能否优化一下安卓13，有root，有XP

**Comment by jestyf** [comment]
似乎是因为安卓13进一步加强了权限的管理，我手上没有安卓13的设备，暂时无法测试，抱歉。等有安卓13设备之后我再来更新

**Comment by jestyf** [comment]
似乎是因为安卓13进一步加强了权限的管理，我手上没有安卓13的设备，暂时无法测试，抱歉。等有安卓13设备之后我再来更新
